name: Upload dags to S3

on:
  push:
    branches: []

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::509809506113:role/mwaa-github-action
          aws-region: eu-central-1

      - name: Upload to S3
        run: |
          aws s3 sync dags s3://r-mor-airflow-config-staging/dags
          aws s3 sync requirements s3://r-mor-airflow-config-staging/python_requirements
